### ISSUE TITLE
basic install 

### ISSUE THREAD

**Issue by sa7adv** [sixuniform/yousdr#1]
Hi ..  im new to this :-)  But i have a issue how to install .  following install txt ,  but i dont have any /var/www/"yousdr"  catalog on my rasp .

**Comment by sixuniform** [comment]
Hi!

cd /var/www  , if this directory doesn't exist, either install the apache package first, or simply run:
mkdir /var/www  
then cd /var/www

Then start from the top of the readme, using "git clone..." will create the "yousdr" directory and download all of it's components.

/Rick
